import { MessageCircleMore, ShieldAlert, Star, UsersRound } from 'lucide-react';

import { Card } from '@/components/ui/Card';
import { COPY } from '@/constants/app';
import { DashboardStats } from '@/types/dashboard';

export interface StatsGridProps {
  readonly stats: DashboardStats;
}

export const StatsGrid = ({ stats }: StatsGridProps): JSX.Element => {
  return (
    <section className="grid gap-4 lg:grid-cols-4">
      <Card
        title={COPY.teamMembers}
        value={`${stats.activeUsers}/${stats.totalSeats}`}
        subtitle={COPY.seatUsage}
        icon={<UsersRound className="h-5 w-5" />}
      />
      <Card
        title="Queries Today"
        value={stats.queriesToday.toString()}
        subtitle={`+${stats.queriesChangePercent}% from yesterday`}
        icon={<MessageCircleMore className="h-5 w-5" />}
      />
      <Card
        title="Guardrail Alerts"
        value={stats.guardrailAlerts.toString()}
        subtitle="Policy events requiring review"
        icon={<ShieldAlert className="h-5 w-5" />}
      />
      <Card
        title="Images Created"
        value={stats.imagesCreated.toString()}
        subtitle="Generated by the team today"
        icon={<Star className="h-5 w-5" />}
      />
    </section>
  );
};
